name: Docker Build

on:
  push:
    branches:
      - main # Change this to your main branch or other relevant branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-username/your-image-name:latest .
